services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.debug
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.debug
    ports:
      - "3001:3001"
      - "9229:9229"
    volumes:
      - ./config.yaml:/app/config/config.yaml
      - ./data:/app/config/data
    environment:
      - CONFIG_PATH=/app/config/config.yaml