# Use Node.js LTS version
FROM node:20

WORKDIR /app
RUN mkdir -p /app/config
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
# Expose debugging port
EXPOSE 9229

# Command to run the application in debug mode with hot reloading
CMD ["npm", "run", "dev"]